# Generated by Django 4.2.7 on 2025-11-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='ArticlePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('est_approuve', models.BooleanField(default=True, verbose_name='Avis approuvé')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Clients',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('en_preparation', 'En préparation'), ('prete', 'Prête pour livraison'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (FCFA)')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('latitude_livraison', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude livraison')),
                ('longitude_livraison', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude livraison')),
                ('instructions_livraison', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('methode_paiement', models.CharField(choices=[('paygate', 'PayGate'), ('espece', 'Espèce à la livraison'), ('mobile_money', 'Mobile Money')], default='espece', max_length=20, verbose_name='Méthode de paiement')),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut du paiement')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence de commande')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='clients.client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='clients.client')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
    ]
