# Generated by Django 4.2.7 on 2025-11-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('commercants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_favoris', to='commercants.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='commercant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_recues', to='commercants.commercant'),
        ),
    ]
