# Generated by Django 4.2.7 on 2025-11-06 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('commercants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='clients.client'),
        ),
        migrations.AddField(
            model_name='avis',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='commercants.produit'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.panier'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercants.produit'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='clients.commande'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercants.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('client', 'produit')},
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('client', 'produit')},
        ),
        migrations.AlterUniqueTogether(
            name='articlepanier',
            unique_together={('panier', 'produit')},
        ),
    ]
