# Generated by Django 4.2.7 on 2025-11-06 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='point_livraison',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Point de livraison'),
        ),
    ]
