# Generated by Django 5.2.8 on 2025-11-14 17:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_commande_point_livraison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='instructions_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='latitude_livraison',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='longitude_livraison',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('paygate', 'PayGate'), ('espece', 'Espèce à la livraison'), ('mobile_money', 'Mobile Money')], default='espece', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='point_livraison',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('en_preparation', 'En préparation'), ('prete', 'Prête pour livraison'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
