# Generated by Django 5.2.8 on 2025-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paygate_network',
            field=models.CharField(blank=True, choices=[('FLOOZ', 'FLOOZ'), ('TMONEY', 'T-Money')], max_length=10, null=True, verbose_name='Réseau mobile'),
        ),
        migrations.AddField(
            model_name='commande',
            name='paygate_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='paygate_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence PayGate'),
        ),
        migrations.AddField(
            model_name='commande',
            name='paygate_status',
            field=models.CharField(choices=[('initie', 'Paiement initié'), ('en_attente', 'En attente de paiement'), ('paye', 'Paiement confirmé'), ('echec', 'Échec du paiement'), ('expire', 'Paiement expiré'), ('annule', 'Paiement annulé')], default='en_attente', max_length=20, verbose_name='Statut PayGate'),
        ),
    ]
