# Generated by Django 5.2.8 on 2025-11-14 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_commande_paygate_network_commande_paygate_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('paygate', 'PayGate'), ('espece', 'Espèce à la livraison'), ('mobile_money', 'Mobile Money'), ('portefeuille', 'Portefeuille')], default='espece', max_length=20),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_commande', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_plateforme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_commercant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('est_transfere', models.BooleanField(default=False)),
                ('date_transfert', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='clients.commande')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
            },
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde disponible (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='DepotPortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('paygate', 'PayGate (Carte)'), ('virement', 'Virement Bancaire'), ('espece', 'Dépôt en Espèces')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('numero_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('operateur', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='clients.portefeuille')),
            ],
            options={
                'verbose_name': 'Dépôt Portefeuille',
                'verbose_name_plural': 'Dépôts Portefeuille',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='RetraitCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement Bancaire'), ('espece', 'Retrait en Espèces')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echec', 'Échec'), ('traite', 'Traité')], default='en_attente', max_length=20)),
                ('numero_compte', models.CharField(blank=True, max_length=100, null=True)),
                ('operateur', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_beneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('frais_retrait', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='clients.portefeuille')),
            ],
            options={
                'verbose_name': 'Retrait Commerçant',
                'verbose_name_plural': 'Retraits Commerçants',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction Portefeuille',
                'verbose_name_plural': 'Transactions Portefeuille',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
