# Generated by Django 5.2.8 on 2025-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_commande_methode_paiement_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitcommercant',
            name='operateur',
            field=models.CharField(blank=True, choices=[('FLOOZ', 'FLOOZ'), ('TMONEY', 'T-Money')], max_length=20, null=True),
        ),
    ]
