# Generated by Django 5.2.8 on 2025-11-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_retraitcommercant_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitcommercant',
            name='numero_transaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
