# Generated by Django 4.2.7 on 2025-11-06 10:46

from decimal import Decimal
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis_conduire', models.ImageField(upload_to='permis/')),
                ('carte_grise', models.ImageField(upload_to='cartes_grises/')),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('velo', 'Vélo'), ('scooter', 'Scooter')], default='moto', max_length=50)),
                ('immatriculation', models.CharField(max_length=20)),
                ('est_disponible', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_en_ligne', models.BooleanField(default=False)),
                ('position_actuelle', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('derniere_position_mise_a_jour', models.DateTimeField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_livraisons', models.PositiveIntegerField(default=0)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouvelle_livraison', 'Nouvelle livraison disponible'), ('livraison_acceptee', 'Livraison acceptée'), ('livraison_terminee', 'Livraison terminée'), ('paiement', 'Paiement reçu'), ('systeme', 'Notification système')], max_length=30, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='livraisons.livreur')),
            ],
            options={
                'verbose_name': 'Notification du livreur',
                'verbose_name_plural': 'Notifications des livreurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('attribuee', 'Attribuée'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours de livraison'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('echec', 'Échec')], default='attribuee', max_length=20, verbose_name='Statut de la livraison')),
                ('date_attribution', models.DateTimeField(blank=True, null=True, verbose_name="Date d'attribution")),
                ('date_acceptation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('date_debut_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de début de livraison')),
                ('date_fin_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de livraison')),
                ('cout_livraison', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Coût de livraison (FCFA)')),
                ('distance_estimee', models.FloatField(blank=True, null=True, verbose_name='Distance estimée (km)')),
                ('duree_estimee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (minutes)')),
                ('adresse_livraison_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point de livraison')),
                ('boutique_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point de la boutique')),
                ('instructions_speciales', models.TextField(blank=True, verbose_name='Instructions spéciales de livraison')),
                ('preuve_livraison', models.ImageField(blank=True, null=True, upload_to='preuves_livraison/', verbose_name='Preuve de livraison')),
                ('signature_client', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature du client')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='clients.commande', verbose_name='Commande associée')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='livraisons.livreur', verbose_name='Livreur assigné')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_attribution'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('ponctualite', models.PositiveIntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], verbose_name='Ponctualité')),
                ('professionalisme', models.PositiveIntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], verbose_name='Professionalisme')),
                ('securite', models.PositiveIntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], verbose_name='Sécurité du colis')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='livraisons.livraison')),
            ],
            options={
                'verbose_name': 'Évaluation du livreur',
                'verbose_name_plural': 'Évaluations des livreurs',
            },
        ),
        migrations.CreateModel(
            name='PositionLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Position')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('vitesse', models.FloatField(blank=True, null=True, verbose_name='Vitesse (km/h)')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='livraisons.livreur')),
            ],
            options={
                'verbose_name': 'Position du livreur',
                'verbose_name_plural': 'Positions des livreurs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['livreur', 'timestamp'], name='livraisons__livreur_654541_idx')],
            },
        ),
    ]
