# Generated by Django 4.2.7 on 2025-11-06 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to=settings.AUTH_USER_MODEL),
        ),
    ]
