# Generated by Django 5.2.8 on 2025-11-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0002_alter_livreur_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementProbleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('route_barree', 'Route barrée'), ('adresse_incorrecte', 'Adresse incorrecte'), ('trafic_extreme', 'Trafic extrême'), ('danger', 'Danger / Accident'), ('client_absent', 'Client absent'), ('colis_endommage', 'Colis endommagé'), ('autre', 'Autre problème')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolu', models.BooleanField(default=False)),
                ('livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livraisons.livraison')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraisons.livreur')),
            ],
            options={
                'verbose_name': 'Signalement de problème',
                'verbose_name_plural': 'Signalements de problèmes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
