# Generated by Django 5.2.8 on 2025-11-17 16:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0003_signalementprobleme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmeOptimisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parametres', models.JSONField(default=dict)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('icone', models.CharField(default='moto', max_length=50)),
                ('vitesse_moyenne', models.FloatField(default=25.0)),
                ('capacite_chargement', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('consommation', models.FloatField(default=0.05)),
                ('tarif_multipliateur', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('polygone', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('tarif_base', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('delai_estime', models.PositiveIntegerField(default=30)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
            },
        ),
        migrations.AddField(
            model_name='livreur',
            name='competences_speciales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='livreur',
            name='date_dernier_entretien',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='kilometrage_vehicule',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='livreur',
            name='niveau_batterie',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='TourneeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('distance_totale', models.FloatField(default=0.0)),
                ('duree_estimee', models.PositiveIntegerField(default=0)),
                ('gain_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('livraisons', models.ManyToManyField(related_name='tournees', to='livraisons.livraison')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraisons.livreur')),
            ],
            options={
                'verbose_name': 'Tournée de livraison',
                'verbose_name_plural': 'Tournées de livraison',
            },
        ),
        migrations.AddField(
            model_name='livreur',
            name='type_vehicule_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraisons.typevehicule'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='zone_affectee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraisons.zonelivraison'),
        ),
    ]
