# Generated by Django 5.2.8 on 2025-11-23 09:50

import django.contrib.gis.db.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0004_algorithmeoptimisation_typevehicule_zonelivraison_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationlivreur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificationlivreur',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='positionlivreur',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='signalementprobleme',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='tourneelivraison',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='positionlivreur',
            name='livraisons__livreur_654541_idx',
        ),
        migrations.AddField(
            model_name='livraison',
            name='donnees_google_maps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livraison',
            name='polyline_itineraire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourneelivraison',
            name='donnees_optimisation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tourneelivraison',
            name='polyline_tournee',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluationlivreur',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluationlivreur',
            name='date_evaluation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluationlivreur',
            name='note',
            field=models.PositiveIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')]),
        ),
        migrations.AlterField(
            model_name='evaluationlivreur',
            name='ponctualite',
            field=models.PositiveIntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')]),
        ),
        migrations.AlterField(
            model_name='evaluationlivreur',
            name='professionalisme',
            field=models.PositiveIntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')]),
        ),
        migrations.AlterField(
            model_name='evaluationlivreur',
            name='securite',
            field=models.PositiveIntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='adresse_livraison_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='boutique_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='cout_livraison',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_attribution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_debut_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_fin_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='distance_estimee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='duree_estimee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='instructions_speciales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='preuve_livraison',
            field=models.ImageField(blank=True, null=True, upload_to='preuves_livraison/'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='signature_client',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='notificationlivreur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationlivreur',
            name='donnees_supplementaires',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationlivreur',
            name='est_lue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationlivreur',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificationlivreur',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationlivreur',
            name='type_notification',
            field=models.CharField(choices=[('nouvelle_livraison', 'Nouvelle livraison disponible'), ('livraison_acceptee', 'Livraison acceptée'), ('livraison_terminee', 'Livraison terminée'), ('paiement', 'Paiement reçu'), ('systeme', 'Notification système')], max_length=30),
        ),
        migrations.AlterField(
            model_name='positionlivreur',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='positionlivreur',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='positionlivreur',
            name='vitesse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
