# Generated by Django 4.2.7 on 2025-11-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('categorie', models.CharField(choices=[('alimentation', 'Alimentation'), ('electronique', 'Électronique'), ('vetements', 'Vêtements'), ('sante', 'Santé et Beauté'), ('maison', 'Maison et Jardin'), ('sport', 'Sport et Loisirs'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description de la boutique')),
                ('photo_boutique', models.ImageField(blank=True, null=True, upload_to='boutiques/', verbose_name='Photo de la boutique')),
                ('horaire_ouverture', models.TimeField(verbose_name="Heure d'ouverture")),
                ('horaire_fermeture', models.TimeField(verbose_name='Heure de fermeture')),
                ('jours_ouverture', models.CharField(default='Lundi-Mardi-Mercredi-Jeudi-Vendredi-Samedi', max_length=100, verbose_name="Jours d'ouverture")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Boutique active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Commerçant',
                'verbose_name_plural': 'Commerçants',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('prix_promotionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promotionnel (FCFA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('stock_min', models.PositiveIntegerField(default=5, verbose_name='Stock minimum alerte')),
                ('categorie', models.CharField(choices=[('alimentaire', 'Produit alimentaire'), ('electronique', 'Électronique'), ('vetement', 'Vêtement'), ('beaute', 'Beauté et soin'), ('maison', 'Maison'), ('sport', 'Sport'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie du produit')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Photo du produit')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Produit actif')),
                ('est_en_promotion', models.BooleanField(default=False, verbose_name='En promotion')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='commercants.commercant')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_reduction', models.PositiveIntegerField(verbose_name='Pourcentage de réduction (%)')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description de la promotion')),
                ('est_active', models.BooleanField(default=True, verbose_name='Promotion active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='commercants.produit')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
