# Generated by Django 5.2.8 on 2025-11-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='commercant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_commercant', to='commercants.commercant'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_produit', to='commercants.produit'),
        ),
    ]
