# Generated by Django 5.2.8 on 2025-11-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercants', '0003_alter_produit_commercant_alter_promotion_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercant',
            name='categorie',
            field=models.CharField(choices=[('alimentaire', 'Alimentaire'), ('electronique', 'Électronique'), ('vetements', 'Vêtements'), ('sante', 'Santé et Beauté'), ('maison', 'Maison et Jardin'), ('sport', 'Sport et Loisirs'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
