# Generated by Django 5.2.8 on 2025-11-18 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('nombre_retraits', models.IntegerField(default=0)),
                ('succes', models.IntegerField(default=0)),
                ('echecs', models.IntegerField(default=0)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lot de Payout',
                'verbose_name_plural': 'Lots de Payout',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('montant_maximum', models.DecimalField(decimal_places=2, default=500000.0, max_digits=10)),
                ('plafond_quotidien', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration Payout',
                'verbose_name_plural': 'Configurations Payout',
            },
        ),
    ]
